[project]
name = "hackatone"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.9.0",
    "crewai[tools]==0.51.0",
    "cryptography>=45.0.5",
    "gtts>=2.5.4",
    "huggingface-hub>=0.33.4",
    "keyring>=25.6.0",
    "opencv-python>=4.11.0.86",
    "sentencepiece>=0.2.0",
    "transformers>=4.53.3",
]
